global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

#alerting:
#  alertmanagers:
#  - scheme: http
#    static_configs:
#    - targets:
#      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s

    static_configs:
         - targets: ['localhost:9090']
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - pushgateway:9091
  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
         - targets: ['node-exporter:9100']
  - job_name: 'dotnet-example'
    scrape_interval: 15s
    static_configs:
         - targets: ['172.17.0.1:1234', '172.17.0.2:1235']
